export const TYPES = {
  CREATE_DATA: "CREATE_DATA",
  READ_ALL_DATA: "READ_ALL_DATA",
  READ_ONE_DATE: "READ_ONE_DATE",
  UPDATE_DATA: "UPDATE_DATA",
  DELETE_DATA: "DELETE_DATA",
  NO_DATA: "NO DATA",
};
